POST http://localhost:8080/student
Content-Type: application/json

{
  "firstName": "Trey",
  "lastName": "Smith",
  "nickname": "tiger",
  "calendarId": "qwerty@group.calendar.google.com"
}

###

POST http://localhost:8080/teacher
Content-Type: application/json

{
  "firstName": "Ashley",
  "lastName": "Sarver",
  "nickname": "Ashley"
}

###

POST http://localhost:8080/student/subject
Content-Type: application/json

{
  "studentId": "6403e570ffe7eb0ff530105b",
  "subjects": [
    {
      "name": "Track",
      "pricePerHour": 267.22
    },
    {
      "name": "History",
      "pricePerHour": 20.78
    },
    {
      "name": "Group Meeting",
      "pricePerHour": 12.56
    },
    {
      "name": "Dance",
      "pricePerHour": 78.09
    }
  ]
}

###
POST http://localhost:8080/student/subjects
Content-Type: application/json

{
  "studentId": "640599a4fcd7ba07c3b1d4f0",
  "subjects": [
    {
      "name": "HOMEWORK: Math",
      "pricePerHour": 2
    },
    {
      "name": "TYPING PRACTICE",
      "pricePerHour": 1587
    }
  ]
}

###
GET http://localhost:8080/student/6403e570ffe7eb0ff530105b

###
GET http://localhost:8080/teacher/6403e582ffe7eb0ff530105c

###
GET http://localhost:8080/students

###
GET http://localhost:8080/teachers

### - local time
POST http://localhost:8080/excel
Content-Type: application/json

{
  "minLocalTime": "2023-02-27T07:59:59-05:00",
  "maxLocalTime": "2023-03-03T19:00:01-05:00"
}

### - UTC time
POST http://localhost:8080/excel
Content-Type: application/json

{
  "minLocalTime": "2023-03-10T05:00:00Z",
  "maxLocalTime": "2023-03-11T04:59:59Z"
}

###
GET http://localhost:8080/excel

###
GET http://localhost:8080/excel/file.xlsx

###
GET http://localhost:8080/excel/EclipseAcademy_February_2023.xlsx
