POST http://localhost:8080/student
Content-Type: application/json

{
  "firstName": "Jack",
  "lastName": "Btesh",
  "nickname": "Jack",
  "calendarId": "c_ath9g8cs5n551v6ve3b96m6tio@group.calendar.google.com"
}

###

POST http://localhost:8080/teacher
Content-Type: application/json

{
  "firstName": "Ashley",
  "lastName": "Sarver",
  "nickname": "Ashley"
}

###

POST http://localhost:8080/student/subject
Content-Type: application/json

{
  "studentId": "6403e570ffe7eb0ff530105b",
  "subjects": [
    {
      "name": "Track",
      "pricePerHour": 267.22
    },
    {
      "name": "History",
      "pricePerHour": 20.78
    },
    {
      "name": "Group Meeting",
      "pricePerHour": 12.56
    },
    {
      "name": "Dance",
      "pricePerHour": 78.09
    }
  ]
}

###
GET http://localhost:8080/student/6403e570ffe7eb0ff530105b

###
GET http://localhost:8080/teacher/6403e582ffe7eb0ff530105c

###
GET http://localhost:8080/students

###
GET http://localhost:8080/teachers
